wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1668130246
    t:
      1:
      - 1
      - 41
      - 54
      - 55
      2:
      - 1
      - 41
      - 54
      - 55
      3:
      - 5
      - 14
      4: 3.7.0
      5: 0.12.17
      8:
      - 3
      - 5
checkpoint_interval:
  desc: null
  value: 1
conf_thres:
  desc: null
  value: 0.1
data:
  desc: null
  value: config/custom.data
epochs:
  desc: null
  value: 2000
evaluation_interval:
  desc: null
  value: 1
iou_thres:
  desc: null
  value: 0.5
logdir:
  desc: null
  value: logs
model:
  desc: null
  value: config/yolov3 copy.cfg
multiscale_training:
  desc: null
  value: false
n_cpu:
  desc: null
  value: 8
nms_thres:
  desc: null
  value: 0.5
optimizer:
  desc: null
  value: null
pretrained_weights:
  desc: null
  value: checkpoints\yolov3_ckpt_68.pth
seed:
  desc: null
  value: -1
verbose:
  desc: null
  value: false
